# Generated by Django 3.0.5 on 2020-04-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='photo_data',
            field=models.TextField(),
        ),
    ]
